config/routes.rb
require 'subdomain'

Badgnet::Application.routes.draw do

  constraints(APISubdomain) do
    match '/' => "sites#home" # for now - will probably point to some help doc
    namespace :v1 do
      match '/' => "sites#home" # for now - will probably point to some help doc
      controller :clients do
        match '/clients/badges' => :badges, :via => :get
        match '/clients/feats' => :feats, :via => :get
      end
      controller :users do
        match '/users/badges' => :badges, :via => :get
        match '/users/feats' => :feats, :via => :get
      end
      controller :feats do
        match '/feats/log' => :log, :via => :post
      end
      controller :reports do
        match 'reports/client' => :client, :via => :get
        match 'reports/badges' => :badges, :via => :get
        match 'reports/feats' => :feats, :via => :get
      end
    end
  end
  
  namespace :client do
    scope :via => :get do
      match '/' => :home
      match '/home' => :home
      match '/login' => :login
      match '/logout' => :logout
      match '/signup' => :signup
      match '/activate' => :activate
      match '/reactivate' => :reactivate
      match '/account'  => :account
      match '/change_email' => :change_email
      match '/change_password' => :change_password
      match '/forgot_password' => :forgot_password
      match '/badges' => :badges
      match '/badge' => :new_badge, :as => :new_badge
      match '/badge/:id' => :edit_badge, :as => :edit_badge
      match '/feat' => :new_feat, :as => :new_feat
      match '/feat/:id' => :edit_feat, :as => :edit_feat
      match '/images' => :images
    end
    scope :via => :post do
      match '/home' => :home
      match '/login' => :login
      match '/signup' => :signup
      match '/reactivate' => :reactivate
      match '/account' => :account
      match '/change_email' => :change_email
      match '/change_password' => :change_password
      match '/forgot_password' => :forgot_password
      match '/badge' => :create_badge, :as => :create_badge
      match '/badge/:id' => :update_badge, :as => :update_badge
      match '/feat' => :create_feat, :as => :create_feat
      match '/feat/:id' => :update_feat, :as => :update_feat
      match '/images' => :images_submit, :as => :images_submit
    end
  end
  
  namespace :admin do
    match '/', :to => "admin#index", :as => :home
    resources :clients do
      post 'multi_update', :on => :collection
      post 'generate_api_key', :on => :member
    end
  end

  match '/privacy', :to => "application#privacy"
  match '/tos', :to => "application#tos"
  
  root :to => "sites#home"

end

app/controllers/admin/clients_controller.rb
module Admin
  
  class ClientsController < AdminController

    def index

      @limit = params[:limit] || 100
      @id = params[:id] ? params[:id].strip : ""
      @name = params[:name] ? params[:name].strip : ""
      @username = params[:username] ? params[:username].strip : ""
      @show_inactive = params[:show_inactive] ? true : false

      conditions = {}
      
      if @name != ""
        conditions[:name] = @name  
      end
      
      if @username != ""
        conditions[:username] = @username
      end
      
      if @id != ""
        conditions[:id] = @id
      end
      
      if !@show_inactive
        conditions[:active] = true
      end

      @clients = Client.find(:all, :limit => @limit, :conditions => conditions)
    end     

    def multi_update
      # Update multiple clients at the same time      
      unless params[:client_id]
        flash[:error] = "You must select at least one client"
        return redirect_to(admin_clients_url)
      end
      
      clients = Client.find(params[:client_id])
      if params['activate']  
        clients.each { |c| c.update_attribute(:active, true) }
      end
      
      if params['inactivate']  
        clients.each { |c| c.update_attribute(:active, false) }
      end      
      
      flash[:notice] = "Clients updated."

      redirect_to(:back)
    end
    
    def show
      @client = Client.find(params[:id])
    end
    
    def generate_api_key
      client = Client.find(params[:id])
      unless client.api_key
        if client.update_attributes(:api_key => Client.generate_api_key)
          flash[:message] = "API Key generated."
        else
          flash[:error] = "There was an error generating the API Key. Please try again."
        end
      end
      redirect_to(admin_client_url(client))
    end
    
  end
  
end

app/controllers/client_controller.rb
require 'gchart'

class ClientController < ApplicationController
  before_filter :login_required, :except => [:signup, :forgot_password, :activate, :reactivate, :login, :logout]

  # Use the client layout
  layout "client"

  # Badge methods
  def badges
    @badges = Badge.find(:all, 
      :conditions => {:client_id => @current_client.id }, 
      :order => 'active desc, created_at desc')
    @feats = Feat.find(:all, 
      :conditions => {:client_id => @current_client.id },
      :order => 'active desc, created_at desc')
    @image_rows = BadgeImage.find(:all, 
      :conditions => {:client_id => @current_client.id },
      :order => 'active desc, created_at asc').in_groups_of(4, false)
  end

  def new_badge
    @badge = Badge.new
    
    group_count = 10
    
    @official_images = BadgeImage.find(:all, 
      :conditions => {:client_id => nil, :active => true}).in_groups_of(group_count, false)
    @selected_image = { @official_images[0][0].id => "selected" }
    @badge.badge_image_id = @official_images[0][0].id 
    @client_images = BadgeImage.find(:all, 
      :conditions => {:client_id => @current_client.id, :active => true}).in_groups_of(group_count, false)

    @client_feats = Feat.find(:all, :conditions => {:client_id => @current_client.id, :active => true })      
    @feats = []
    render :badge_form
  end

  def create_badge    
    begin
      Badge.transaction do
        # Create Badge
        active = params[:active].nil? ? false : params[:active]
        badge = Badge.new(:name => params[:name], :description => params[:description],
          :badge_image_id => params[:badge_image_id], :active => active,
          :client_id => @current_client.id)
        badge.save!
        # Create each BadgesFeat
        feats = params[:feats]
        thresholds = params[:thresholds]
        unless feats.nil?
          for i in (0..feats.length-1)
            bf = BadgesFeat.new(:badge_id => badge.id, :feat_id => feats[i], :threshold => thresholds[i])
            bf.save!
          end
        end
      end
      flash[:message] = "Your badge was created successfully."
      redirect_to :action => :badges
    rescue ActiveRecord::RecordInvalid => invalid
      ### TODO: add invalid.record.errors?
      flash[:error] = "There was a problem creating your badge."
      redirect_to :action => :new_badge     
    end
  end

  def edit_badge
    @badge = Badge.find(params[:id])
    
    group_count = 10
    
    @official_images = BadgeImage.find(:all, 
      :conditions => {:client_id => nil, :active => true}).in_groups_of(group_count, false)
    @selected_image = { @badge.badge_image_id => "selected" }
    @client_images = BadgeImage.find(:all, 
      :conditions => {:client_id => @current_client.id, :active => true}).in_groups_of(group_count, false)
    
    @client_feats = Feat.find(:all, :conditions => {:client_id => @current_client.id, :active => true })
    @feats = @badge.badges_feats(:include => :feat)
    render :badge_form
  end

  def update_badge
    badge = Badge.find(params[:id])
    begin
      Badge.transaction do
        # Update badge
        active = params[:active].nil? ? false : params[:active]
        badge.update_attributes!(:name => params[:name], :description => params[:description],
          :badge_image_id => params[:badge_image_id], :active => active, 
          :client_id => @current_client.id)
        # Delete all current feats
        BadgesFeat.delete_all(:badge_id => badge.id)
        # Create each BadgesFeat
        feats = params[:feats]
        thresholds = params[:thresholds]
        unless feats.nil?
          for i in (0..feats.length-1)
            bf = BadgesFeat.new(:badge_id => badge.id, :feat_id => feats[i], :threshold => thresholds[i])
            bf.save!
          end
        end
      end
      flash[:message] = "Your badge was updated successfully."
      redirect_to :action => :badges
    rescue ActiveRecord::RecordInvalid => invalid
      ### TODO: add invalid.record.errors?
      flash[:error] = "There was a problem updating your badge."
      redirect_to :action => :edit_badge
    end
  end
  
  # Feat methods
  def new_feat
    @feat = Feat.new()
    render :feat_form
  end

  def create_feat
    begin
      feat = Feat.create(:name => params[:name], :client_id => @current_client.id)
      feat.save!
      flash[:message] = "Your feat was created successfully."
      redirect_to :action => :badges
    rescue ActiveRecord::RecordInvalid => invalid
      ### TODO: add invalid.record.errors?
      flash[:error] = "There was a problem creating your feat."
      redirect_to :action => :new_feat
    end
  end

  def edit_feat
    @feat = Feat.find(params[:id])
    render :feat_form
  end

  def update_feat
    feat = Feat.find(params[:id])
    begin
      feat.update_attributes!(:name => params[:name], :client_id => @current_client.id)
      feat.save!
      flash[:message] = "Your feat was updated successfully."
      redirect_to :action => :badges
    rescue ActiveRecord::RecordInvalid => invalid
      ### TODO: add invalid.record.errors?
      flash[:error] = "There was a problem updating your feat."
      redirect_to :action => :edit_feat 
    end
  end
  
  # BadgeImage methods
  def images
    @images = BadgeImage.find(:all, :conditions => {:client_id => @current_client.id, :active => true })
  end

  def images_submit    
    bi = BadgeImage.create(:image => params[:badge_image], :client_id => @current_client.id)

    if bi.errors.empty?
      @result = { :result => "success", :message => "Image succesfully uploaded!", :url => bi.image(:thumb) }
    else
      @result = { :result => "error", :message => bi.errors.full_messages.join(", ")}
    end
    render :layout => false
  end

  def home
    use_default = false
    
    if request.post?
      if verify_date(params[:start_day]) && verify_date(params[:end_day])
        start_date = Time.zone.parse(params[:start_day]).to_date
        end_date = Time.zone.parse(params[:end_day]).to_date

        if start_date > end_date
          use_default = true
          flash.now[:warning] = "Start Day cannot be after End Day."
        end
        if end_date - start_date + 1 > 365
          use_default = true
          flash.now[:warning] = "Date range cannot be greater than 1 year."
        end
      else
        use_default = true
        flash.now[:error] = "Dates must be of the form: MM/DD/YY"
      end
    else # request.get
      use_default = true
    end

    if use_default
      # default to last 7 days
      start_date = 1.days.ago.to_date - 6.days
      end_date = 1.days.ago.to_date
    end
    
    @num_days = end_date - start_date + 1
    
    @total_stats = ClientStat.total_stats(@current_client.id, start_date, end_date)
    client_stats = ClientStat.find(:all, 
      :conditions => {:client_id => @current_client.id, :day => start_date..end_date},
      :order => "day asc")
    @table_stats = []
    if client_stats.length > 0
      table_stats = ClientStat.fill_in_zeros(client_stats, @current_client.id, start_date, end_date)
      p table_stats
      chart_stats = ClientStat.chart_format(table_stats)
      p chart_stats
      @chart_url = Gchart.line(
        :size => '450x350',
        :title => 'BadgMe Activity',
        :data => chart_stats[:data],
        :axis_with_labels => ['x','y'],
        :axis_labels => chart_stats[:axis_labels],
        :line_colors => ['60b0db','FFCC33'],
        :legend => ['Feats','Badges'],
        :min_value => 0,
        :max_value => chart_stats[:max_value])
      # blue: '60b0db'
      # dark-blue: '3b5998'
      # light-yellow: 'FAF7E3'
      # dark-yellow: 'FFCC33'
    end
    
    @top_badges = UserBadge.top_badges(@current_client.id, start_date, end_date)[0,5]
    @top_feats = UserFeat.top_feats(@current_client.id, start_date, end_date)[0,5]
  
    @start_day = start_date.strftime(OPTIONS[:date_format])
    @end_day = end_date.strftime(OPTIONS[:date_format])
  end
  
  # Account methods
  def account
    @client = Client.find(@current_client.id)
    if request.post?
      if @client.update_attributes(:name => params[:name], :time_zone => params[:time_zone])
        flash[:message] = "Your account has been updated."
      else
        flash[:warning] = "Could not update account. Please try again."
      end
    end
  end

  def signup    
    @client = Client.new()
    if request.post?
      c = Client.new(:name => params[:name], :username => params[:username], 
        :password => params[:password], :password_confirmation => params[:password_confirmation],
        :email => params[:email], :time_zone => params[:time_zone])
      # Captcha validation
      unless verify_recaptcha(:private_key => OPTIONS[:recaptcha_private_key])      
        flash[:warning] = "Invalid captcha results. Please try again."
        render(:action => :signup)
        return
      end
      if c.save and c.send_activation()
          flash[:message] = "Signup successful. An activation code has been sent by email."
          redirect_to :action =>'login'
      else
        flash[:warning] = "Signup unsuccessful."
      end
    end
  end

  def login
    @client = Client.new()
    if request.post?
      c = Client.authenticate(params[:username], params[:password])
      if c.nil?
        flash[:warning] = "Login unsuccessful."
      else
        if c.active
          if c.activated
            initialize_client_session(c.id)      
             flash[:message]  = "Login successful."
            redirect_to_stored
          else
            flash[:warning] = "You must activate your account."
            redirect_to :action => :reactivate
          end
        else
          flash[:warning] = "Your account is no longer active. Please contact customer support."
        end
      end
    end
  end

  def logout
    initialize_client_session(nil)
    flash[:message] = 'Logged out.'
    redirect_to :action => 'login'
  end

  def forgot_password
    if request.post?

app/controllers/v1/clients_controller.rb
module V1

  class ClientsController < ApiController

    def badges
      success(@current_client.active_badges)
    end
    
    def feats
      success(@current_client.active_feats)    
    end
   
  end
  
end

app/views/client/account.html.erb
<%= error_messages_for 'client' %><br/>

<%= form_tag(client_account_url, :method => "post") do %>

	<h3 class="header">Account Info</h3>
	<div class="section">
		<div class="action_buttons">
		<%= link_to "Change Password", client_change_password_url, :class => "action_button" %>
		<%= link_to "Change Email", client_change_email_url, :class => "action_button" %>
		</div>
		<table>
			<tr>
				<td><%= label_tag 'Id' %></td> 
				<td>
					<%= label_tag "", @client.id %>
				</td>
			</tr>
			<tr>
				<td><%= label_tag 'Company Name', 'Company Name' %></td> 
				<td>
					<%= text_field_tag :name, @client.name, :class => "required", :maxlength => 50 %>
				</td>
			</tr>
			<tr>
				<td><%= label_tag 'Username' %></td> 
				<td>
					<%= label_tag "", @client.username %>
				</td>
			</tr>
			<tr>
				<td><%= label_tag 'Email' %></td> 
				<td>
					<%= label_tag "", @client.email %>
				</td>
			</tr>
			<tr>
				<td><%= label_tag 'API Key', 'API Key' %></td> 
				<td>
					<%= label_tag "", @client.api_key %>
				</td>
			</tr>
			<tr>
				<td><%= label_tag 'Time Zone', 'Time Zone' %></td> 
				<td>
					<%= label_tag "", @client.time_zone %>
				</td>
			</tr>			
		</table>
	</div>
	<div style="margin: 10px 0 0;">
		<%= content_tag :button, "Update Account", :type => :submit, :class => :submit_button %>
		or <%= link_to "cancel", client_home_url %>
	</div>
<% end %>

app/views/client/badge_form.html.erb
<%= form_tag(controller.action_name == 'new_badge' ? client_create_badge_url : client_update_badge_url, 
	:method => "post", :id => "create_badge_form") do %>
	<h3 class="header">Official BadgNet Images</h3>	
	<div class="section">
		<%= render :partial => "image_selector", :locals => { :image_rows => @official_images } %>
	</div>

	<% if @client_images.length > 0 %>
	<h3 class="header">Your Images</h3>
	<div class="section">
		<%= render :partial => "image_selector", :locals => { :image_rows => @client_images } %>
	</div>
	<% end %>

	<h3 class="header">Badge Info</h3>
	<div class="section">
		<table>
			<% if @badge.id %>
				<tr>
					<td><%= label_tag 'Id' %></td> 
					<td>
						<%= label_tag "", @badge.id %>
					</td>
				</tr>
			<% end%>
			<tr>
				<td><%= label_tag 'Name' %></td> 
				<td>
					<%= text_field_tag :name, @badge.name, :class => "required", 
						:maxlength => 30 %>
				</td>
			</tr>
			<tr>
				<td><%= label_tag 'Description' %></td> 
				<td>
					<%= text_field_tag :description, @badge.description, :class => "required",
						:maxlength => 50 %>
				</td>
			</tr>
			<tr>
				<td><%= label_tag 'Active' %></td> 
				<td>
					<%= check_box_tag :active, "1", @badge.active, :class => "required" %>
				</td>
			</tr>
		</table>
	</div>

	<h3 class="header">Feats</h3>
	<div class="section">
		<table id="feat_table">
			<tr>
				<th>Feat</th>
				<th>Threshold</th>
				<th><input type="button" value="Add Feat" 
					onclick="add_feat_row(<%= options_from_collection_for_select(@client_feats, "id", "name").to_json %>);" >
				</th>
			</tr>
			<% if @feats.length > 0 %>	
				<% for f in @feats %>
					<tr>
						<td><%= select_tag "feats[]", options_from_collection_for_select(@client_feats, "id", "name", f.feat.id) %></td>
						<td><%= text_field_tag "thresholds[]", f.threshold %></td>
						<td><input type='button' value='Remove' onclick='remove_feat_row(this);'></td>
					</tr>
				<% end %>
			<% end %>
		</table>
		<% if @feats.length == 0 %>
			<div id="noFeats">You haven't attached any feats to this badge yet.</div>
		<% end %>
	</div>

	<%= hidden_field_tag :badge_image_id, @badge.badge_image_id %>

	<div style="margin: 10px 0 0;">
		<%= content_tag :button, controller.action_name == 'new_badge' ? "Create Badge" : "Update Badge",
			:type => :submit, :class => :submit_button %>
		or <%= link_to "cancel", client_badges_url %>
	</div>

<% end %>

app/views/client/badges.html.erb
<div class="left" id="badge_list">
	<div id="full_badges">		
		<div class="section_header">
			<span>Badges</span>
			<%= link_to "New Badge", client_new_badge_url, :id => "new_item_button" %>
			<div class="clear"></div>
		</div>
		<div>
		<ul class="image_list">
		<% if @badges.length > 0 %>
			<% for b in @badges %>
				<li>
				<div class="full_badge">
					<div class="image">
						<%= link_to image_tag(b.get_image, :class => "badge_image"),
						 	client_edit_badge_url(b.id) %>
					</div>
					<div class="left badge_info">
						<div class="name"><%= b.name %></div>
						<div class="desc"><%= b.description %></div>
					</div>
					<div class="left badge_status">
						<%= b.display_active %>
					</div>
					<div class="clear"></div>
				</div>
				</li>
			<% end %>
			</ul>
		<% end %>
		<% if @badges.length == 0 %>
			<div>You haven't created any badges yet.</div>
		<% end %>
		</div>
	</div>
</div>

<div class="left" id="feat_list">	
	<div class="section_header">
		<span>Feats</span>
		<%= link_to "New Feat", client_new_feat_url, :id => "new_item_button" %>
		<div class="clear"></div>
	</div>
	<div class="full_feat">
		<% if @feats.length > 0 %>
			<ul class="list">
				<% for f in @feats %>				
				<li>
					<div class="feat_info">
						<div class="name"><%= link_to f.name, client_edit_feat_url(f.id) %></div>
					</div>
				</li>
				<% end %>
			</ul>
		<% else %>			
			<div>You haven't created any feats yet.</div>
		<% end %>
	</div>
</div>

<div class="left" id="image_list">	
	<div class="section_header">
		<span>Images</span>
		<%= link_to "Upload Image", client_images_url, :id => "new_item_button" %>
		<div class="clear"></div>
	</div>
	<div>
		<ul class="image_list">
			<% for image_row in @image_rows %>
			<li>
				<% for i in image_row %>
					<div class="image">
						<%= image_tag i.image(:thumb), :class => "badge_image" %>
					</div>
				<% end %>
				<div class="clear"></div>
			</li>
			<% end%>
		</ul>
		<% if @image_rows.empty? %>
			<div>You haven't uploaded any images yet.</div>
		<% end %>
	</div>
</div>

app/views/client/change_email.html.erb
<%= error_messages_for 'client' %>

<%= form_tag :action => 'change_email' %>

<h3 class="header">Change Email</h3>
<div class="section">
	<div class="note"> NOTE: If you change your email, you will have to re-activate your account. </div>
	<table>
		<tr>
			<td><%= label_tag 'New Email' %></td> 
			<td>
				<%= text_field_tag :email, "" %>
			</td>
		</tr>
	</table>
</div>

<div style="margin: 10px 0 0;">
	<%= content_tag :button, 'Change Email', :type => :submit, :class => :submit_button %>
	or <%= link_to "cancel", client_account_url %>
</div>

app/views/client/change_password.html.erb
<%= error_messages_for 'client' %>

<%= form_tag :action => 'change_password' %>

<h3 class="header">Change Password</h3>
<div class="section">
	<table>
		<tr>
			<td><%= label_tag 'Choose Password' %></td> 
			<td>
				<%= password_field_tag :password, "" %>
			</td>
		</tr>
		<tr>
			<td><%= label_tag 'Confirm Password' %></td> 
			<td>
				<%= password_field_tag :password_confirmation, "" %>
			</td>
		</tr>
	</table>
</div>

<div style="margin: 10px 0 0;">
	<%= content_tag :button, 'Change Password', :type => :submit, :class => :submit_button %>
	or <%= link_to "cancel", client_account_url %>
</div>

app/views/client/feat_form.html.erb
<div><%= flash[:notice] %></div>

<%= form_tag(controller.action_name == 'new_feat' ? client_create_feat_url : client_update_feat_url, 
	:method => "post", :id => "create_badge_form") do %>

	<h3 class="header">Feat Info</h3>
	<div class="section">
		<table>
			<% if @feat.id %>
				<tr>
					<td><%= label_tag 'Id' %></td> 
					<td>
						<%= label_tag "", @feat.id %>
					</td>
				</tr>
			<% end %>
			<tr>
				<td><%= label_tag 'Name' %></td> 
				<td>
					<%= text_field_tag :name, @feat.name, :class => "required", 
						:maxlength => 30 %>
				</td>
			</tr>
		</table>
	</div>

	<div style="margin: 10px 0 0;">
		<%= content_tag :button, controller.action_name == 'new_feat' ? "Create Feat" : "Update Feat",
			:type => :submit, :class => :submit_button %>
		or <%= link_to "cancel", client_badges_url %>
	</div>

<% end %>

app/views/client/forgot_password.html.erb
<%= form_tag :action => 'forgot_password' %>

<h3 class="header">Forgotten Password</h3>
<div class="section">
	<table>
		<tr>
			<td><%= label_tag 'Username' %></td> 
			<td>
				<%= text_field_tag :username, "" %>
			</td>
		</tr>
		<tr>
			<td><%= label_tag 'Email' %></td> 
			<td>
				<%= text_field_tag :email, "" %>
			</td>
		</tr>
	</table>
</div>

<div style="margin: 10px 0 0;">
	<%= content_tag :button, 'Send Password', :type => :submit, :class => :submit_button %>
	or <%= link_to "cancel", client_login_url %>
</div>

app/views/client/home.html.erb
<%= form_tag(client_home_url, :method => "post") do %>
	<div class="left image_section">
		<div class="right">
			<%= label_tag 'Start Day', 'Start Day'%>
			<%= text_field_tag :start_day, @start_day, :class => :date_field %>
			<%= label_tag 'End Day', 'End Day'%>
			<%= text_field_tag :end_day, @end_day, :class => :date_field %>
			<%= content_tag :button, "Submit", :type => :submit, :class => :submit_button %>
		</div>
		<div class="left">
			<% if @chart_url %>
				<%= image_tag(@chart_url) %>
			<% else %>
				<div class="center" id="no_data">No data for this date range.</div>
			<% end %>
		</div>
	</div>
	<div class="left section" id="total_stats">
		<h3 class="header">Total Activity</h3>
		<table>
			<tr>
				<th>Days</th>
				<th>Feats</th>
				<th>Badges</th>
			</tr>
			<tr>
				<td><%= @num_days %></td>
				<td><%= @total_stats[:feats] %></td>			
				<td><%= @total_stats[:badges] %></td>
			</tr>
		</table>
	</div>
	<div class="left section" id="top_badges">
		<h3 class="header">Top Badges</h3>
		<% if @top_badges.length > 0 %>
			<table>
				<tr>
					<th>Badge</th>
					<th>Awarded</th>
				</tr>
				<% for badge in @top_badges %>
					<tr>
						<td><%= badge[:badge_name]%></td>
						<td><%= badge[:badges]%></td>
					</tr>
				<% end %>
			</table>
		<% else %>
			<div>No data for this date range.</div>
		<% end %>
	</div>
	<div class="left section" id="top_feats">
		<h3 class="header">Top Feats</h3>
		<% if @top_feats.length > 0 %>
			<table>
				<tr>
					<th>Feat</th>
					<th>Performed</th>
				</tr>
				<% for feat in @top_feats %>
					<tr>
						<td><%= feat[:feat_name]%></td>
						<td><%= feat[:feats]%></td>
					</tr>
				<% end %>
			</table>
		<% else %>
			<div>No data for this date range.</div>
		<% end %>
	</div>		
<% end %>

app/views/client/images.html.erb
<div class="hidden" id="upload_result"></div>

<%= form_tag client_images_url, :method => :post, :multipart => true, :id => "image_upload", 
	:target => "upload_target" do %>

<h3 class="header">Your Badge Images</h3>

<div class="section">
	<% if @images.length > 0 %>
	<ul class="image_list">
		<% for i in @images %>
		<li>
			<div class="left image">
			<%= image_tag i.image(:thumb), :class => "badge_image" %>
			</div>
		</li>
		<% end %>
		<div class="clear"></div>
	</ul>
	<% else %>
	<div id="noImages">You haven't uploaded any images yet.</div>
	<% end %>
</div>

<iframe id="upload_target" name="upload_target" src="" style="width: 0; height: 0;" class="hidden"></iframe>

<h3 class="header">Upload Badge Image</h3>
<div class="section">
		<table>
			<tr>
				<th><%= label_tag :badge_image, "File to upload" %></th>
				<td><%= file_field_tag :badge_image, :class => "required" %></td>
			</tr>
		</table>
		<div style="margin: 15px 0 0">
		<%= content_tag :button, "Upload Badge Image", :type => :submit, :class => :submit_button %>
		or <%= link_to "cancel", client_badges_url %>
		</div>
</div>

<div style="margin: 10px 0;" id="image_conditions">
	<p>Image Conditions</p>
	<ul>
		<li>Images must be one of these types: <%= BadgeImage::CONTENT_TYPES.join(", ") %>.</li>
		<li>Max image size is <%= number_to_human_size BadgeImage::MAX_IMAGE_SIZE %>.</li>
		<li>We reserve the right to take down any image.</li>
	</ul>
</div>
<% end %>

app/views/client/reactivate.html.erb
<%= form_tag :action=>'reactivate'%>

<div class="note">Your account has not been activated. Please check your email, including the junk mail folder, 
	or resend your activation email below. </div>

<h3 class="header">Resend Activation Code</h3>
<div class="section">
	<table>
		<tr>
			<td><%= label_tag 'Username' %></td> 
			<td>
				<%= text_field_tag :username, "" %>
			</td>
		</tr>
		<tr>
			<td><%= label_tag 'Email' %></td> 
			<td>
				<%= text_field_tag :email, "" %>
			</td>
		</tr>
	</table>
</div>

<div style="margin: 10px 0 0;">
	<%= content_tag :button, 'Send Activation Code', :type => :submit, :class => :submit_button %>
	or <%= link_to "cancel", client_login_url %>
</div>