config/routes.rb
require 'subdomain'

Badgnet::Application.routes.draw do

  constraints(APISubdomain) do
    match '/' => "sites#home" # for now - will probably point to some help doc
    namespace :v1 do
      match '/' => "sites#home" # for now - will probably point to some help doc
      controller :clients do
        match '/clients/badges' => :badges, :via => :get
        match '/clients/feats' => :feats, :via => :get
      end
      controller :users do
        match '/users/badges' => :badges, :via => :get
        match '/users/feats' => :feats, :via => :get
      end
      controller :feats do
        match '/feats/log' => :log, :via => :post
      end
      controller :reports do
        match 'reports/client' => :client, :via => :get
        match 'reports/badges' => :badges, :via => :get
        match 'reports/feats' => :feats, :via => :get
      end
    end
  end
  
  namespace :client do
    scope :via => :get do
      match '/' => :home
      match '/home' => :home
      match '/login' => :login
      match '/logout' => :logout
      match '/signup' => :signup
      match '/activate' => :activate
      match '/reactivate' => :reactivate
      match '/account'  => :account
      match '/change_email' => :change_email
      match '/change_password' => :change_password
      match '/forgot_password' => :forgot_password
      match '/badges' => :badges
      match '/badge' => :new_badge, :as => :new_badge
      match '/badge/:id' => :edit_badge, :as => :edit_badge
      match '/feat' => :new_feat, :as => :new_feat
      match '/feat/:id' => :edit_feat, :as => :edit_feat
      match '/images' => :images
    end
    scope :via => :post do
      match '/home' => :home
      match '/login' => :login
      match '/signup' => :signup
      match '/reactivate' => :reactivate
      match '/account' => :account
      match '/change_email' => :change_email
      match '/change_password' => :change_password
      match '/forgot_password' => :forgot_password
      match '/badge' => :create_badge, :as => :create_badge
      match '/badge/:id' => :update_badge, :as => :update_badge
      match '/feat' => :create_feat, :as => :create_feat
      match '/feat/:id' => :update_feat, :as => :update_feat
      match '/images' => :images_submit, :as => :images_submit
    end
  end
  
  namespace :admin do
    match '/', :to => "admin#index", :as => :home
    resources :clients do
      post 'multi_update', :on => :collection
      post 'generate_api_key', :on => :member
    end
  end

  match '/privacy', :to => "application#privacy"
  match '/tos', :to => "application#tos"
  
  root :to => "sites#home"

end

app/views/layouts/admin.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
		<title>Badgnet</title>
	  	<%= raw stylesheet_link_tag 'screen', :media => "screen" %>
	  	<%= raw stylesheet_link_tag 'print', :media => "print" %>	
	  	<%= raw stylesheet_link_tag 'global' %>
	  	<%= raw stylesheet_link_tag 'admin/admin' %>
		<%= javascript_include_tag "rails" %>
		<%= javascript_include_tag "global" %>	
		<%= yield(:head) %>
	</head>

	<body id="<%= controller.controller_name %>_<%= controller.action_name %>">
		<div id="container">
			<div id="body">
				<div id="header">
					<div id="nav">
						<%= link_to "Admin Home", admin_home_url %> | <%= link_to "Badgnet Home", root_url %>
					</div>
				</div>
				<div id="content"><%= yield %></div>
			</div>
		</div>		
	</body>
</html>

app/views/layouts/client.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>BadgNet</title>
	  <%= raw stylesheet_link_tag 'screen', :media => "screen" %>
	  <%= raw stylesheet_link_tag 'print', :media => "print" %>	
	  <%= raw stylesheet_link_tag 'global' %>	
	  <%= raw stylesheet_link_tag 'application' %>		
	  <%= raw stylesheet_link_tag 'badge' %>	
	  <%= csrf_meta_tag %>
	</head>
	<body id="<%= controller.controller_name %>_<%= controller.action_name %>">

	<div id="wrapper">
		<div id="header">
			<%= link_to image_tag("spacer.gif", :id => "logo"), root_url %>
			<div class="right nav">
				<div style="text-align: right; margin-bottom: 5px;">
				<% if @current_client %>
					<span id="welcome">
						welcome, <%= @current_client.name %> 
						<%= link_to "[logout]", client_logout_url %>
					</span>
				<% end %>
				</div>
				<% if @current_client %>
				<div>
					<%= link_to "Home", client_home_url %>
					<%= link_to "Badges", client_badges_url %>
					<%= link_to "Account", client_account_url %>
				</div>
				<% end %>
			</div>
			<div class="clear"></div>
		</div>

		<div id="content">
			<div><%= flash[:notice] %></div>
			<div><%= flash[:message] %></div>
			<div><%= flash[:warning] %></div>
			<div><%= flash[:error] %></div>
			<%= yield %>
		</div>
		<div id="footer">
			<!-- <%= link_to "privacy", privacy_url %> -->
			<!-- <%= link_to "terms of service", tos_url %> -->
		</div>
	</div>
	<%= yield(:body_scripts) %>
	<div id="fb-root"></div>
	
	<%= raw javascript_include_tag "mootools-core-1.3-full-compat" %>
	<%= raw javascript_include_tag "mootools-more-1.3-full-compat" %>
	<%= raw javascript_include_tag "rails" %>
	<%= raw javascript_include_tag "global" %>
	<%= raw javascript_include_tag "modal" %>
	<%= raw javascript_include_tag "overlay" %>
	<%= raw javascript_include_tag "client" %>	
	<%= raw javascript_include_tag "ejs" %>
	<%= raw javascript_include_tag "view" %>
	<% if @current_user %>
	<script type="text/javascript">
		/* Useful info when doing javascript queries */
		var fb_id = <%= @current_user.get_facebook_id %>;
		var group = <%= @current_user.is_group? %>;
	</script>
	<% end %>
</body>
</html>

app/views/layouts/sites.html.erb
<!DOCTYPE html>
<html>
	<head>
	<meta name="google-site-verification" content="jUclv9E0TVa8B_krzf-8_EkEmcWsit1FZwaQSaK4_-I" />
	  <title>Badgnet</title>
	  <%= raw stylesheet_link_tag 'screen', :media => "screen" %>
	  <%= raw stylesheet_link_tag 'print', :media => "print" %>	
	  <%= raw stylesheet_link_tag 'global' %>
	  <%= raw stylesheet_link_tag 'application' %>	
	  <%= csrf_meta_tag %>
	</head>
	<body id="<%= controller.controller_name %>_<%= controller.action_name %>">
		<h1>BadgNet</h1>

		<ul>
			<li><%= link_to "Client Login", client_login_url %></li>

		</ul>
		<%= yield(:body_scripts) %>
		<div id="fb-root"></div>
		<script src="http://connect.facebook.net/en_US/all.js"></script>
		<script>
			FB.init({appId: <%= OPTIONS[:facebook_app_id] %>, status: true, cookie: true, xfbml: true});
		</script>

		<%= raw javascript_include_tag "mootools-core-1.3-full-compat" %>
		<%= raw javascript_include_tag "mootools-more-1.3-full-compat" %>
		<%= raw javascript_include_tag "rails" %>
		<%= raw javascript_include_tag "global" %>
		<%= raw javascript_include_tag "modal" %>
		<%= raw javascript_include_tag "overlay" %>
		<%= raw javascript_include_tag "ejs" %>
		<%= raw javascript_include_tag "view" %>
		<% if @current_user %>
		<script type="text/javascript">
			/* Useful info when doing javascript queries */
			var fb_id = <%= @current_user.get_facebook_id %>;
			var group = <%= @current_user.is_group? %>;
		</script>
		<% end %>
	</body>
</html>	